name: Debug
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "."
      - name: Lint
        uses: ./
        with:
          version: latest
          args: lint
      - name: Mage
        uses: ./
        with:
          version: latest
          args: mage
